### ISSUE TITLE
bootstrap fails on first run due to recent postgres image security requirement

### ISSUE THREAD

**Issue by s-chand** [eHealthAfrica/aether-bootstrap#150]
Hey guys,

So I tried setting this up following the instructions in the README file. I ran into two issues:

- the db doesn't start up. This was related to a recent update to postgres. See here [link](https://stackoverflow.com/questions/60420940/how-to-fix-error-error-database-is-uninitialized-and-superuser-password-is-not)
- the url for aether UI should be started without the trailing slash included in the documentation. `http://ui.aether.local` works but this `http://ui.aether.local/` doesn't. The latter redirects to nginx's default home page the first time it was run. Having logged in now, it works as expected with or without the trailing slash. :+1: Looking good!

**Comment by obdulia-losantos** [comment]
Hi @s-chand :wave: 

Which `README` are you "reading"? :thinking: 

- The DB issue was fixed 6 months ago #125 
- The url `http://ui.aether.local/` is no longer in use, nowadays is `http://aether.local/dev/kernel-ui` (with or without trailing slash)

Thanks!

**Comment by s-chand** [comment]
Hey Obdulia, I used the guide on the Aether website.

**Comment by obdulia-losantos** [comment]
Noted!
