### ISSUE TITLE
Fails to complete ./scripts/init.sh --- ERROR: for kong  Cannot create container for service kong: bad format for add-host: ":127.0.0.1"

### ISSUE THREAD

**Issue by LarryEitel** [eHealthAfrica/aether-bootstrap#171]
`
=================================================================== Starting database server...
============================================================================ database is ready!
The KONG_PG_PASSWORD variable is not set. Defaulting to a blank string.
The KONG_IP variable is not set. Defaulting to a blank string.
The BASE_DOMAIN variable is not set. Defaulting to a blank string.
The KEYCLOAK_PG_PASSWORD variable is not set. Defaulting to a blank string.
The KEYCLOAK_GLOBAL_ADMIN variable is not set. Defaulting to a blank string.
The KEYCLOAK_GLOBAL_PASSWORD variable is not set. Defaulting to a blank string.
The BASE_PROTOCOL variable is not set. Defaulting to a blank string.
The KEYCLOAK_INTERNAL variable is not set. Defaulting to a blank string.
The KONG_INTERNAL variable is not set. Defaulting to a blank string.
The ZOOKEEPER_ROOT_USER variable is not set. Defaulting to a blank string.
The ZOOKEEPER_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
The KAFKA_SECRET variable is not set. Defaulting to a blank string.
The CC_API_USER variable is not set. Defaulting to a blank string.
The CC_API_PASSWORD variable is not set. Defaulting to a blank string.
The CC_CLUSTER_NAME variable is not set. Defaulting to a blank string.
The ELASTICSEARCH_PASSWORD variable is not set. Defaulting to a blank string.
The KONGA_PG_PASSWORD variable is not set. Defaulting to a blank string.
Creating network "auth_default" with the default driver
Creating volume "auth_theme_ehealth" with default driver
Creating auth_kong_run ...
Creating auth_kong_run ... error

ERROR: for auth_kong_run  Cannot create container for service kong: bad format for add-host: ":127.0.0.1"

ERROR: for kong  Cannot create container for service kong: bad format for add-host: ":127.0.0.1"
Encountered errors while bringing up the project.
`

**Comment by obdulia-losantos** [comment]
@LarryEitel this happens with the latest docker version. If that is the case, please, use the [chore-docker](https://github.com/eHealthAfrica/aether-bootstrap/tree/chore-docker) branch.
